apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "kia01.xh3b4sd.giantswarm.io"
spec:
  dnsNames:
    - "kia01.xh3b4sd.giantswarm.io"
  duration: "2160h"
  issuerRef:
    kind: "ClusterIssuer"
    name: "letsencrypt-demo"
  renewBefore: "360h"
  secretName: "ingressgateway"
