apiVersion: "networking.istio.io/v1beta1"
kind: "Gateway"
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  selector:
    istio: "ingressgateway"
  servers:
    - port:
        name: "grpc"
        number: 443
        protocol: "HTTPS"
      hosts:
        - "kia01.aws.venturemark.co"
      tls:
        mode: "SIMPLE"
        credentialName: "ingressgateway"
